# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Mohamed Hammad

[package]
name = "loran-render"
description = "Loran — Markdown to terminal renderer (text and TUI)."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
pulldown-cmark = { workspace = true }

[lints]
workspace = true
