# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Mohamed Hammad

[package]
name = "loran-index"
description = "Loran — index builder and Ingestor trait abstraction."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["man", "help", "info", "tldr", "index"]
categories = ["parser-implementations", "development-tools"]

[dependencies]
loran-pages = { path = "../loran-pages", version = "0.4.0" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
wait-timeout = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
