# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Mohamed Hammad

[package]
name = "loran-cli"
description = "Loran — the Steelbore reference manual (CLI binary)."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[[bin]]
name = "loran"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
is-terminal = { workspace = true }
jiff = { workspace = true }
loran-core = { path = "../loran-core" }
loran-index = { path = "../loran-index" }
loran-pages = { path = "../loran-pages" }
loran-render = { path = "../loran-render" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
insta = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
