// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Mohamed Hammad

//! `loran schema` — emit a JSON Schema document describing every
//! public Loran data type.
//!
//! Phase 3 (WP-P3.01) replaces the Phase 1 placeholder with a real
//! schema generated by `schemars` directly from the typed Rust
//! structures. The output is Draft 2020-12 compatible and is the
//! source of truth consumed by the MCP server (WP-P3.02) for the
//! `tools/get` reply and by external agents for envelope validation.
//!
//! Sub-keys:
//!
//! - no arg → emit the full document with every type in `$defs`.
//! - `page` / `overlay-page` / `show` / `find` / `search` /
//!   `categories` / `category` / `update` → emit only the named
//!   sub-schema (for `tools/get` and for documentation snippets).

use std::collections::BTreeMap;
use std::process::ExitCode;

use loran_core::{
    BodyBlock, Categories, CategoryEntry, FindResult, IntroBlock, ScoredMatch, SearchResult,
    ShowResult, UpdateOutcome,
};
use loran_pages::{OverlayPage, Page};
use schemars::schema::RootSchema;
use schemars::schema_for;
use serde_json::{Value, json};

use crate::cli::{Cli, SchemaArgs};
use crate::exit::ExitCode as LoranExit;

const DRAFT_2020_12: &str = "https://json-schema.org/draft/2020-12/schema";

pub(crate) fn run(_cli: &Cli, args: &SchemaArgs) -> ExitCode {
    let document = match args.key.as_deref() {
        None | Some("all") => full_document(),
        Some(key) => {
            if let Some(schema) = sub_schema(key) {
                schema
            } else {
                eprintln!("error: unknown schema key `{key}`");
                eprintln!(
                    "  hint: try one of: page, overlay-page, show, find, search, categories, category, update"
                );
                return ExitCode::from(LoranExit::UsageError.to_process_code());
            }
        }
    };

    let rendered = serde_json::to_string_pretty(&document).unwrap_or_else(|_| document.to_string());
    println!("{rendered}");
    ExitCode::from(0)
}

/// Full schema document: every type in `$defs`, plus a top-level
/// `properties` block keyed by sub-command response name so callers
/// can navigate "what does `loran show` emit?" in one hop.
fn full_document() -> Value {
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    for (name, root) in defs_table() {
        defs.insert(name.to_owned(), root_to_json(root));
    }
    json!({
        "$schema": DRAFT_2020_12,
        "$id": "https://Loran.Steelbore.com/schema/v1.json",
        "title": "Loran data-type registry",
        "description":
            "JSON Schema Draft 2020-12 covering every public Loran data type. \
             Each `$defs` entry is the schema for one Rust type re-exported \
             by `loran-core` or `loran-pages`. Sub-command response bodies \
             (`loran show`, `loran find`, …) are referenced under \
             `responses` for quick navigation.",
        "type": "object",
        "$defs": defs,
        "responses": responses_map(),
    })
}

/// Per-sub-command response-shape pointers. `tools/call` in MCP can
/// consult this to learn which `$defs` entry a verb's data payload
/// matches.
fn responses_map() -> Value {
    json!({
        "show":       { "$ref": "#/$defs/ShowResult" },
        "find":       { "$ref": "#/$defs/FindResult" },
        "search":     { "$ref": "#/$defs/SearchResult" },
        "categories": { "$ref": "#/$defs/Categories" },
        "list":       { "type": "array", "items": { "$ref": "#/$defs/Page" } },
        "update":     { "$ref": "#/$defs/UpdateOutcome" },
    })
}

/// Emit a single sub-schema for the named key. Returns `None` for
/// unknown keys so the caller can surface a usage hint.
fn sub_schema(key: &str) -> Option<Value> {
    let root = defs_table()
        .into_iter()
        .find(|(name, _)| key.eq_ignore_ascii_case(name) || canonical_alias(name) == key)?
        .1;
    let mut document = root_to_json(root);
    if let Some(obj) = document.as_object_mut() {
        obj.insert(
            "$schema".to_owned(),
            Value::String(DRAFT_2020_12.to_owned()),
        );
    }
    Some(document)
}

/// Map the kebab-case CLI key to the `$defs` `PascalCase` name.
fn canonical_alias(defs_name: &str) -> String {
    let mut out = String::with_capacity(defs_name.len() + 4);
    for (i, ch) in defs_name.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('-');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// The list of `$defs` entries — pair the schemars `RootSchema` with
/// the canonical name we want under `$defs`.
fn defs_table() -> Vec<(&'static str, RootSchema)> {
    vec![
        ("Page", schema_for!(Page)),
        ("OverlayPage", schema_for!(OverlayPage)),
        ("IntroBlock", schema_for!(IntroBlock)),
        ("BodyBlock", schema_for!(BodyBlock)),
        ("ShowResult", schema_for!(ShowResult)),
        ("FindResult", schema_for!(FindResult)),
        ("ScoredMatch", schema_for!(ScoredMatch)),
        ("SearchResult", schema_for!(SearchResult)),
        ("CategoryEntry", schema_for!(CategoryEntry)),
        ("Categories", schema_for!(Categories)),
        ("UpdateOutcome", schema_for!(UpdateOutcome)),
    ]
}

/// schemars 0.8 emits Draft 07. Convert the `RootSchema` to a JSON
/// value and stamp the Draft 2020-12 meta-schema URL so downstream
/// consumers validate against the right version. The serialised
/// shape is forward-compatible — Draft 2020-12 accepts everything
/// schemars emits at the structural level.
fn root_to_json(root: RootSchema) -> Value {
    let mut value = serde_json::to_value(root).unwrap_or(Value::Null);
    if let Some(obj) = value.as_object_mut() {
        obj.remove("$schema");
    }
    value
}

#[cfg(test)]
mod tests {
    use super::{canonical_alias, full_document, sub_schema};

    #[test]
    fn full_document_advertises_draft_2020_12() {
        let doc = full_document();
        assert_eq!(
            doc.pointer("/$schema").and_then(|v| v.as_str()),
            Some("https://json-schema.org/draft/2020-12/schema")
        );
    }

    #[test]
    fn full_document_includes_every_def() {
        let doc = full_document();
        for name in [
            "Page",
            "OverlayPage",
            "IntroBlock",
            "BodyBlock",
            "ShowResult",
            "FindResult",
            "ScoredMatch",
            "SearchResult",
            "CategoryEntry",
            "Categories",
            "UpdateOutcome",
        ] {
            assert!(
                doc.pointer(&format!("/$defs/{name}")).is_some(),
                "missing $defs entry for {name}"
            );
        }
    }

    #[test]
    fn responses_map_references_each_verb() {
        let doc = full_document();
        for verb in ["show", "find", "search", "categories", "list", "update"] {
            assert!(
                doc.pointer(&format!("/responses/{verb}")).is_some(),
                "missing response entry for {verb}"
            );
        }
    }

    #[test]
    fn sub_schema_for_page_strips_internal_meta() {
        let page = sub_schema("page").expect("page sub-schema");
        assert_eq!(
            page.pointer("/$schema").and_then(|v| v.as_str()),
            Some("https://json-schema.org/draft/2020-12/schema")
        );
    }

    #[test]
    fn sub_schema_honours_kebab_case() {
        assert!(sub_schema("overlay-page").is_some());
        assert!(sub_schema("show-result").is_some());
    }

    #[test]
    fn sub_schema_returns_none_for_unknown_key() {
        assert!(sub_schema("definitely-not-a-type").is_none());
    }

    #[test]
    fn canonical_alias_kebabs_pascal_case() {
        assert_eq!(canonical_alias("Page"), "page");
        assert_eq!(canonical_alias("OverlayPage"), "overlay-page");
        assert_eq!(canonical_alias("ShowResult"), "show-result");
    }
}
